/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
